Add [rotationQuaternion]
Matway/mpl-sl pull request #31
Opened 2022-07-28 00:05 UTC by 3DpoNCh1k

2022-07-28 11:50 UTC, ValeryAntopol requested changes

2022-07-28 11:50 UTC, ValeryAntopol commented on Quaternion.mpl
> +rotationQuaternion: [rotation: threshold:;; TRUE] [
This overload checks only stack depth and will break if user wants to use 1-arg version when he has more values on uncontrolled stack. I suggest checking that `threshold` is a floating point number.

2022-07-28 11:50 UTC, ValeryAntopol commented on Quaternion.mpl
> +    ) quaternion
This part is done by the `axisAngleQuaternion` above. I suggest reusing the code from this function.

2022-07-28 16:49 UTC, ValeryAntopol approved these changes
LGTM

2022-08-04 20:58 UTC, MatwayBurkow commented on Quaternion.mpl
> +
Redundant newline

2022-09-22 21:57 UTC, Parean approved these changes

2022-09-22 21:57 UTC, merged